### ISSUE TITLE
S3 variables

### ISSUE THREAD

**Issue by jyjohnson** [DavidTanner/aws-beanstalk-publisher#1]
Hi -- could you please help me with the bucket name and key prefix? I created an EB environment and manually created a few application versions. This is the complete path to one of the versions:

https://s3.amazonaws.com/elasticbeanstalk-us-east-1-409408242700/ATL-Code-Camp/AWSDeploymentArchive_ATL-Code-Camp_1.zip

The application name is "ATL Code Camp" and the environment name is "Production".

What do I enter in the plugin?

Thanks for your help!!

**Comment by DavidTanner** [comment]
I am sorry, I didn't get an email so I just saw this.  The prefix would be elasticbeanstalk-us-east-1-409408242700
