### ISSUE TITLE
Environments field is not saved

### ISSUE THREAD

**Issue by chapmandu** [DavidTanner/aws-beanstalk-publisher#2]
When adding a deployment into ELB, enter a value into the Environments field and click Save. When going back to configure the saved Job, the Environments field is always empty. Everything else is working well.

Plugin version 0.1.1
Browsers tested Chrome 38.0.2125.111 & Firefox 33.1

**Comment by DavidTanner** [comment]
I am not seeing this issue, I will try some debugging tomorrow.

**Comment by amosschallich** [comment]
Jenkins 1.596
Plugin 0.1.2
Firefox 34.0
I am happy to provide any more details.
The issue is as @chapmandu described it.
Add a ELB deployment build step. Fill it out. Add an environment. Save. It works, but if I got back the "environment" field is empty and if I save again without readding it then it deploys to all environments.
Using us-west-2 (doubtful it matters, but just a little more info).

Thanks, Amos

**Comment by DavidTanner** [comment]
Are there any other fields that aren't saving?  The setup we are using has
never lost the value

**Comment by amosschallich** [comment]
Only environments.

**Comment by DavidTanner** [comment]
Found the bug.  There are two classes that are duplicates of each other.  I fixed the publisher step, but not the build step.  I will get that out asap.

**Comment by DavidTanner** [comment]
Closed with version 0.1.3

**Comment by chapmandu** [comment]
Champ!

**Comment by chapmandu** [comment]
Hi @DavidTanner . Is there an ETA for getting this 0.1.3 into the Jenkins plugin repo? Thanks!

**Comment by DavidTanner** [comment]
Check out the jenkinsci repo.

**Comment by chapmandu** [comment]
Hey Bro, Just a heads up. I updated the plugin via Jenkins admin from 0.1.2 to 0.1.4 and it blitzed all my previous deployment settings. There was a Jenkins system message saying there was a bunch of expired data.. The EB plugin sections were all missing from the configure job screen.

**Comment by DavidTanner** [comment]
I had tested it and it was working.  Can you send me a copy of your config files?

**Comment by DavidTanner** [comment]
The settings aren't gone if it is giving you that error, that means that something didn't cross over correctly.

**Comment by DavidTanner** [comment]
Use version 0.1.6.  The build step will come back.  The settings weren't lost, just not updated by the plugin.  Sorry, another error from having two classes that are copies of each other.  That was why I pulled everything out into the extensions.
