### ISSUE TITLE
Security group SSH rule is open to all

### ISSUE THREAD

**Issue by chapmandu** [DavidTanner/aws-beanstalk-publisher#3]
The plugin seems to automagically modify the elastic beanstalk security group and creates a rule leaving port 22 open to the outside world. 

It would be good to be able to configure ssh security group rules. 

Thanks for the great plugin!

**Comment by DavidTanner** [comment]
You wouldn't happen to know how to go about fixing that?  If you open a pull request I would be happy to review it and get it released.

**Comment by chapmandu** [comment]
I was under the impression that your plugin created the ssh rule? If not, perhaps the AWS API creates it for the EB security group.. though it's unusual that Amazon would create such an open rule by default.. 

I'd like to be of more help but I'm not a Java developer.. Sorry..

**Comment by DavidTanner** [comment]
The only thing it does is use the AWS sdk to request and send data to s3, and elastic beanstalk.
